### ISSUE TITLE
CI issue: should the publish.yml workflow really run on PRs?

### ISSUE THREAD

**Issue by joanise** [ReadAlongs/Studio-Web-archived#10]
currently, `.github/workflows/publish.yml` has on:

```
on:
  pull_request:
  push:
    branches:
      - main
```
but I think that should only be on push to main, is that correct?
